### ISSUE TITLE
RuntimeError: Property msg is only availablefor a single message in msgs

### ISSUE THREAD

**Issue by monkeyshichi** [camel-ai/camel#228]
### Required prerequisites

- [X] I have read the documentation <https://camel-ai.github.io/camel/camel.html>.
- [X] I have searched the [Issue Tracker](https://github.com/camel-ai/camel/issues) and [Discussions](https://github.com/camel-ai/camel/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [X] Consider asking first in a [Discussion](https://github.com/camel-ai/camel/discussions/new).

### Questions

i run role_playing.py under ai_society . RuntimeError: Property msg is only availablefor a single message in msgs

**Comment by Obs01ete** [comment]
Hi @monkeyshichi. Thanks for reporting the issue! Could you share the launch command and the stack trace?

**Comment by monkeyshichi** [comment]
> Hi @monkeyshichi. Thanks for reporting the issue! Could you share the launch command and the stack trace?

@dataclass(frozen=True)
class ChatAgentResponse:
    r"""Response of a ChatAgent.

    Attributes:
        msgs (List[BaseMessage]): A list of zero, one or several messages.
            If the list is empty, there is some error in message generation.
            If the list has one message, this is normal mode.
            If the list has several messages, this is the critic mode.
        terminated (bool): A boolean indicating whether the agent decided
            to terminate the chat session.
        info (Dict[str, Any]): Extra information about the chat message.
    """
    msgs: List[BaseMessage]
    terminated: bool
    info: Dict[str, Any]

    @property
    def msg(self):
        if len(self.msgs) != 1:
            raise RuntimeError("Property msg is only available"
                               "for a single message in msgs")
        return self.msgs[0]

**Comment by monkeyshichi** [comment]
Traceback (most recent call last):
  File "C:\Users\DELL\Downloads\ChatGPT-main\camel-real\role_playing.py", line 79, in <module>
    main()
  File "C:\Users\DELL\Downloads\ChatGPT-main\camel-real\role_playing.py", line 56, in main
    input_assistant_msg = assistant_response.msg
  File "C:\Users\DELL\Downloads\ChatGPT-main\camel-real\camel\agents\chat_agent.py", line 57, in msg
    return self.msgs[0]
IndexError: list index out of range

Process finished with exit code 1

**Comment by MorphlingEd** [comment]
> Traceback (most recent call last): File "C:\Users\DELL\Downloads\ChatGPT-main\camel-real\role_playing.py", line 79, in main() File "C:\Users\DELL\Downloads\ChatGPT-main\camel-real\role_playing.py", line 56, in main input_assistant_msg = assistant_response.msg File "C:\Users\DELL\Downloads\ChatGPT-main\camel-real\camel\agents\chat_agent.py", line 57, in msg return self.msgs[0] IndexError: list index out of range
> 
> Process finished with exit code 1

Thanks for your reporting. But from this traceback, it seems the response does not contain any message (`len(self.msgs) == 0`) instead of containing multiple ones, which results in `list index out of range`.  May I ask whether you modified any of the input prompts in `role_playing.py`? That is a strange case as I can still run this script correctly.

**Comment by monkeyshichi** [comment]
> > Traceback (most recent call last): File "C:\Users\DELL\Downloads\ChatGPT-main\camel-real\role_playing.py", line 79, in main() File "C:\Users\DELL\Downloads\ChatGPT-main\camel-real\role_playing.py", line 56, in main input_assistant_msg = assistant_response.msg File "C:\Users\DELL\Downloads\ChatGPT-main\camel-real\camel\agents\chat_agent.py", line 57, in msg return self.msgs[0] IndexError: list index out of range
> > Process finished with exit code 1
> 
> Thanks for your reporting. But from this traceback, it seems the response does not contain any message (`len(self.msgs) == 0`) instead of containing multiple ones, which results in `list index out of range`. May I ask whether you modified any of the input prompts in `role_playing.py`? That is a strange case as I can still run this script correctly.

No,i don't modified any code.

**Comment by monkeyshichi** [comment]
Sorry, maybe because my chatgpt ran out of api, I'll try recharging

**Comment by monkeyshichi** [comment]
But the first time I made that mistake, my chatgpt didn't ran out of api

**Comment by lightaime** [comment]
@Obs01ete could you have a look at this? Thanks!

**Comment by monkeyshichi** [comment]
> @monkeyshichi Please share the instruction to reproduce the crash. Do you have any try-except in your code?

python ai_society/role_playing.py.i don't have any try-except .i just use the same code,i don't modify code.

**Comment by Obs01ete** [comment]
> > @monkeyshichi Please share the instruction to reproduce the crash. Do you have any try-except in your code?
> 
> python ai_society/role_playing.py.i don't have any try-except .i just use the same code,i don't modify code except comment these code: #if len(self.msgs) != 1: #raise RuntimeError("Property msg is only available for a single message in msgs") but i don't affect the result.

I suppose something is wrong with your OpenAI API. You get empty messages from OpenAI. We will improve the exception message to be more specific, but fixing your access to OpenAI API you will need to do yourself.

**Comment by monkeyshichi** [comment]
ok thanks,i will try again

**Comment by lightaime** [comment]
@monkeyshichi The bug is due to the token limit. It is fixed in this commit: https://github.com/camel-ai/camel/commit/9922dd3c0e5aba196a9a8df5f0af8d28317800ee to break the loop when out of token limit. If you want to use a large token limit you can try `ModelType.GPT_3_5_TURBO_16K`. Let me know if you find any question.
