### ISSUE TITLE
[BUG] The model_backend inside ChatAgent directly references the passed model object, which can lead to shared state problems.

### ISSUE THREAD

**Issue by coolbeevip** [camel-ai/camel#973]
### Required prerequisites

- [X] I have read the documentation <https://camel-ai.github.io/camel/camel.html>.
- [X] I have searched the [Issue Tracker](https://github.com/camel-ai/camel/issues) and [Discussions](https://github.com/camel-ai/camel/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [ ] Consider asking first in a [Discussion](https://github.com/camel-ai/camel/discussions/new).

### What version of camel are you using?

0.2.1a

### System information

3.10.12 (main, Aug 16 2023, 15:12:12) [Clang 13.1.6 (clang-1316.0.21.2.5)] darwin
0.2.1a

### Problem description

If a model object is passed in ChatAgent, then the model_backend will directly reference this object.

https://github.com/camel-ai/camel/blob/147161e1fcd6938b8c7ddb82ca07c252325bc254/camel/agents/chat_agent.py#L162

And change the parameters of the model in the following locations.

https://github.com/camel-ai/camel/blob/147161e1fcd6938b8c7ddb82ca07c252325bc254/camel/agents/chat_agent.py#L195

which can lead to shared state problems.

### Reproducible example code

The Python snippets:

The following code will add the tools parameter to the critic agent's model during execution, which causes the critic agent to return multiple options.

```python
  assistant_agent_kwargs = dict(model=model, tools=[*SEARCH_FUNCS])
  user_agent_kwargs = dict(model=model, tools=[*SEARCH_FUNCS])
  critic_kwargs = dict(verbose=True)
  role_play_session = RolePlaying(
      assistant_role_name="Patent Agent",
      user_role_name="Software Engineer",
      critic_role_name="Patent Examiner",
      task_prompt=task_prompt,
      with_task_specify=True,
      with_critic_in_the_loop=True,
      assistant_agent_kwargs=assistant_agent_kwargs,
      user_agent_kwargs=user_agent_kwargs,
      critic_kwargs=critic_kwargs,
      output_language="Chinese",
      model=model,
  )
```

### Traceback

```pytb
Please first enter your choice ([1-3]) and then your explanation and comparison: 


Multiple messages returned in `step()`, message won't be recorded automatically. Please call `record_message()` to record the selected message manually.
Traceback (most recent call last):
  File "/Users/zhanglei/Work/github/storysmith/storysmith/patent_agent.py", line 133, in <module>
    main(model=openai_model, chat_turn_limit=20)
  File "/Users/zhanglei/Work/github/storysmith/storysmith/patent_agent.py", line 60, in main
    assistant_response, user_response = role_play_session.step(input_msg)
  File "/Users/zhanglei/Library/Caches/pypoetry/virtualenvs/storysmith-bTjCBaeI-py3.10/lib/python3.10/site-packages/camel/societies/role_playing.py", line 488, in step
    user_msg = self._reduce_message_options(user_response.msgs)
  File "/Users/zhanglei/Library/Caches/pypoetry/virtualenvs/storysmith-bTjCBaeI-py3.10/lib/python3.10/site-packages/camel/societies/role_playing.py", line 417, in _reduce_message_options
    critic_response = self.critic.reduce_step(messages)
  File "/Users/zhanglei/Library/Caches/pypoetry/virtualenvs/storysmith-bTjCBaeI-py3.10/lib/python3.10/site-packages/camel/agents/critic_agent.py", line 194, in reduce_step
    option = self.get_option(input_msg)
  File "/Users/zhanglei/Library/Caches/pypoetry/virtualenvs/storysmith-bTjCBaeI-py3.10/lib/python3.10/site-packages/camel/agents/critic_agent.py", line 125, in get_option
    critic_msg = critic_response.msg
  File "/Users/zhanglei/Library/Caches/pypoetry/virtualenvs/storysmith-bTjCBaeI-py3.10/lib/python3.10/site-packages/camel/responses/agent_responses.py", line 42, in msg
    raise RuntimeError(
RuntimeError: Property msg is only available for a single message in msgs.
```

### Additional context

CriticAgent also has similar issues.

Perhaps deep copying can be used in the initialization methods of ChatAgent and CriticAgent instead of direct references.

**Comment by coolbeevip** [comment]
I researched the code again and found that when the model parameter is set for rolePlaying, assistant_agent_kwargs, user_agent_kwargs, and critic_kwargs simultaneously, RolePlaying has the highest priority. This is exactly opposite to my initial understanding; I thought that the model parameter in RolePlaying would serve as a default model and would only be used if assistant_agent_kwargs, user_agent_kwargs, and critic_kwargs did not define their own model.

In the above case, after I separately set the model parameter in critic_kwargs, I was able to specify which model it should use.

So this might be a misunderstanding. If you think this isn't a bug, feel free to close it at any time. Alternatively, when users set multiple model parameters at once, you could print a warning log indicating that some of the model parameters will be ignored.
